ADVENTURE_META = {
    "id": "last_voicemail",
    "title": "Last Voicemail",
    "genre": "Horror",
    "description": "A voicemail from an unknown number. The voice is yours. It's warning you about tonight.",
    "estimated_minutes": 5,
    "type": "guided",
    "tags": ["horror", "short", "solo", "suspense"],
    "use_authored_text": True,
}

LANDMARK_BEATS = {
    "vm_connects":      "heard their own voice warn them from the other end",
    "vm_static":        "heard breathing where there should have been silence",
    "vm_loop":          "became part of the loop",
    "vm_check_door":    "looked through the peephole",
    "vm_toaster_check": "crept into the kitchen and heard the knock from 2,000 miles away",
    "vm_confront":      "called out in the dark and heard their own voice answer",
    "end_safe":         "survived the night",
    "end_loop":         "became the voice in the voicemail",
    "end_static":       "dissolved into static",
}

STORY_GRAPH = {

    "intro": {
        "text": (
            "Your phone vibrates against the nightstand. Not a buzz — a sustained, desperate shudder, "
            "like something trapped and frantic inside is trying to claw its way out.\n\n"
            "11:04 PM. Unknown Number. New Voicemail.\n\n"
            "You nearly swipe it away. Your thumb is already moving. But a cold, instinctive dread grips your spine.\n\n"
            "You press play.\n\n"
            "The voice is yours. Not similar. Not close. Yours. It sounds like you've been running. Or hiding.\n\n"
            "\"Don't answer the door tonight.\" A wet, ragged gasp. \"Please… it's already here.\"\n\n"
            "Somewhere in the background of the recording, barely audible — a toaster dings.\n\n"
            "You don't think anything of it."
        ),
        "scene_prompt": (
            "A late-night voicemail from an unknown number. The voice in the recording is the player's own — "
            "breathless, panicked, warning them not to answer the door tonight. In the background of the recording, "
            "barely audible, a toaster dings."
        ),
        "tone": "dread",
        "choices": {
            "check the caller's information": "vm_check_number",
            "call the number back": {
                "type": "rng",
                "outcomes": [
                    {"weight": 50, "next_beat_id": "vm_connects"},
                    {"weight": 35, "next_beat_id": "vm_static"},
                    {"weight": 15, "next_beat_id": "vm_loop"},
                ]
            },
            "put the phone face-down and try to forget it": "vm_ignore",
        },
        "arc": "discovery",
    },

    "vm_check_number": {
        "text": (
            "Eleven digits. No name. No carrier. No country code.\n\n"
            "It looks like a number generated by something that doesn't understand numbers.\n\n"
            "You paste it into your browser. The search bar flickers once — then your phone resets entirely to "
            "the home screen, as if it refused to process the query.\n\n"
            "You open your call log.\n\n"
            "There is no record of any call at 11:04 PM. No missed call. No voicemail notification. "
            "Just a clean, unbroken list of ordinary days.\n\n"
            "The voicemail is still there. Playing fine. But according to every system on your phone, "
            "it was never received."
        ),
        "scene_prompt": (
            "The player is investigating the phone number. Eleven digits, no recognizable format. "
            "A browser search caused the phone to reset to the home screen. The call log shows no record "
            "of any call at 11:04 PM. But the voicemail plays fine."
        ),
        "tone": "discovery",
        "choices": {
            "call the number anyway": {
                "type": "rng",
                "outcomes": [
                    {"weight": 50, "next_beat_id": "vm_connects"},
                    {"weight": 35, "next_beat_id": "vm_static"},
                    {"weight": 15, "next_beat_id": "vm_loop"},
                ]
            },
            "take a screenshot and wait": "vm_clock",
        },
        "arc": "discovery",
    },

    "vm_connects": {
        "text": (
            "One ring. Picked up instantly.\n\n"
            "Silence — and then your own breathing, right in your ear. Shallow. Terrified. "
            "Somehow already knowing you called.\n\n"
            "\"You actually called.\" The other you exhales like it's the first real breath they've taken "
            "in hours. \"Okay. Listen — it's been outside since nine. It looks like someone you know. "
            "It's wearing their face.\"\n\n"
            "\"Don't open the door. Don't go into the hall. Just stay where you are.\"\n\n"
            "The line crackles. Then: \"I have to go. I have to record the message now. Before I lose the number.\"\n\n"
            "The call drops."
        ),
        "scene_prompt": (
            "The player called back the number. Their own voice answered — already knowing they'd call, "
            "already terrified. It warned something has been standing outside since nine PM, wearing the face "
            "of someone familiar. Then it said it had to go record the message — implying the loop is closing "
            "— and the call dropped."
        ),
        "tone": "dread",
        "choices": {
            "\"who does it look like?\" — too late, they're gone": "vm_check_door",
            "\"how are you talking to me right now?\" — too late, they're gone": "vm_asks_self",
            "replay the original voicemail": "vm_replay",
            "go to the front door": "vm_check_door",
        },
        "arc": "confrontation",
    },

    "vm_asks_who": {
        "text": (
            "A long, deliberate pause.\n\n"
            "\"It looks like whoever you'd open the door for,\" your voice says quietly.\n\n"
            "\"That's the point. That's always been the point.\"\n\n"
            "The line dies."
        ),
        "scene_prompt": (
            "The player asked who is outside. Their own voice on the phone answered: it looks like whoever "
            "they would open the door for. That's always been the point. Then the line went dead."
        ),
        "tone": "dread",
        "choices": {
            "check the door": "vm_check_door",
            "barricade yourself and wait": "vm_clock",
        },
        "arc": "confrontation",
    },

    "vm_asks_self": {
        "text": (
            "A long silence. Then, carefully:\n\n"
            "\"The same way you're talking to me right now. The number calls itself. It finds you when it needs to.\"\n\n"
            "A sound in the background — movement, urgent. Like they're checking something.\n\n"
            "\"Listen. It doesn't matter how. What matters is that somewhere between now and 3 AM, you're going "
            "to pick up this phone and say exactly what I said. I don't know how to stop it. "
            "I don't think you can either.\"\n\n"
            "\"Just don't open the door.\"\n\n"
            "The line goes cold."
        ),
        "scene_prompt": (
            "The player asked how this call is possible. Their future self explained the number calls itself "
            "when it needs to. They revealed the player will make this exact call themselves before 3 AM, "
            "and there may be no way to stop it. Then the line went cold."
        ),
        "tone": "threshold",
        "choices": {
            "check the door": "vm_check_door",
            "replay the voicemail": "vm_replay",
            "sit in the dark and wait": "vm_clock",
        },
        "arc": "confrontation",
    },

    "vm_static": {
        "text": (
            "Two rings. Then static — thick and heavy, like breath pressed directly against a microphone.\n\n"
            "Underneath it: slow, patient breathing.\n\n"
            "It never changes pace.\n\n"
            "You wait for it to say something. It doesn't. It just breathes.\n\n"
            "You're not sure how long you sit there listening before you realize it might be waiting "
            "for the same thing from you."
        ),
        "scene_prompt": (
            "The player called back and got static — but underneath, slow patient breathing. "
            "Not human-paced. It never changed. The player isn't sure if they were the one being listened to."
        ),
        "tone": "dread",
        "choices": {
            "check the door": "vm_check_door",
            "play the original voicemail again": "vm_replay",
            "sit in silence and listen to the apartment": "vm_clock",
        },
        "arc": "confrontation",
    },

    "vm_loop": {
        "text": (
            "One ring.\n\n"
            "Then your own voice — mid-sentence — saying the exact words from the voicemail.\n\n"
            "Not a recording. Live. You're already saying them.\n\n"
            "\"Don't answer the door tonight… please… it's already—\"\n\n"
            "You don't remember dialing.\n\n"
            "You don't remember picking up the phone.\n\n"
            "Your hands are shaking. The call timer reads 0:03 seconds and climbing."
        ),
        "scene_prompt": (
            "The player called the number and heard themselves already speaking mid-sentence — "
            "recording the voicemail in real time, with no memory of dialing. "
            "The loop has already begun. The call timer is running."
        ),
        "tone": "threshold",
        "choices": {
            "finish saying the warning": "end_loop",
            "hang up and run to the door": "vm_check_door",
        },
        "arc": "confrontation",
    },

    "vm_replay": {
        "text": (
            "You play the voicemail again, pressing the phone hard against your ear. "
            "Listening differently now. Picking it apart.\n\n"
            "The breathing. The words chosen under pressure. And at the end — that sound you didn't "
            "register the first time.\n\n"
            "A toaster. Somewhere in the background. Distant. Domestic. Completely ordinary.\n\n"
            "You lower the phone.\n\n"
            "When did you last use the toaster?\n\n"
            "Two days ago. Maybe three.\n\n"
            "You play it again.\n\n"
            "This time, there are four extra words at the end —\n"
            "words that weren't there before.\n\n"
            "Your voice says: it can hear the phone.\n\n"
            "You realize the speaker is on."
        ),
        "scene_prompt": (
            "The player replayed the voicemail, listening more carefully. They noticed the toaster sound in "
            "the background for the first time. Playing it again, four new words appeared at the end: "
            "'it can hear the phone.' The speaker was on."
        ),
        "tone": "discovery",
        "choices": {
            "go check the kitchen": "vm_toaster_check",
            "go check the door": "vm_check_door",
            "muffle the phone and wait for morning": "vm_clock",
        },
        "arc": "confrontation",
    },

    "vm_toaster_check": {
        "text": (
            "You move down the hallway in total silence. The floorboards don't creak. They always creak.\n\n"
            "The kitchen is dark except for the blue ghost-light of the microwave clock. The air is wrong — "
            "too cold, faintly metallic, like the smell before a storm.\n\n"
            "The toaster is cold. Untouched. Exactly where you left it.\n\n"
            "Nothing is here. Nothing has been here.\n\n"
            "You almost laugh at yourself.\n\n"
            "Then from the front of the apartment — three slow knocks at the door.\n\n"
            "\"Shave and a haircut,\" a familiar voice says on the other side.\n\n"
            "Your best friend's knock. The one they've used since you were both seventeen. "
            "The friend who moved 2,000 miles away three months ago."
        ),
        "scene_prompt": (
            "The player crept to the kitchen to check the toaster. The floorboards were silent — wrong. "
            "The kitchen was cold and undisturbed. The toaster was off and unused. But then, from the front "
            "of the apartment, came three slow knocks, and a familiar voice said 'Shave and a haircut' — "
            "the knock used by a close friend who moved 2,000 miles away three months ago."
        ),
        "tone": "dread",
        "choices": {
            "go to the peephole": "vm_check_door",
            "call out \"who's there?\"": "vm_confront",
            "back away toward the bedroom": "end_safe",
        },
        "arc": "confrontation",
    },

    "vm_confront": {
        "text": (
            "Your voice echoes unnervingly in the cold kitchen.\n\n"
            "Nothing answers.\n\n"
            "Then — directly behind you, close enough to feel — a whisper in your own voice:\n\n"
            "\"You shouldn't have spoken.\"\n\n"
            "You spin around.\n\n"
            "The kitchen is empty. The toaster is cold. The microwave clock blinks 12:00, "
            "like the power just cut and came back.\n\n"
            "It wasn't here. Now it knows exactly where you are."
        ),
        "scene_prompt": (
            "The player called out in the kitchen. Nothing answered — then their own voice whispered "
            "from directly behind them: 'You shouldn't have spoken.' They spun around to find the kitchen "
            "empty, the microwave clock blinking 12:00 as if power had just cut out."
        ),
        "tone": "dread",
        "choices": {
            "run to the front door": "vm_check_door",
            "barricade the bedroom": "end_safe",
        },
        "arc": "confrontation",
    },

    "vm_ignore": {
        "text": (
            "\"Deepfake,\" you mutter, and put the phone face-down.\n\n"
            "You lie back and stare at the ceiling and try to let the familiar dark do its work.\n\n"
            "The silence feels wrong. Not quiet — thick. Like the air itself is holding its breath.\n\n"
            "At 11:47 PM, three slow knocks echo through the apartment.\n\n"
            "Shave and a haircut. Two bits.\n\n"
            "Your best friend's knock. Exactly. From 2,000 miles away."
        ),
        "scene_prompt": (
            "The player dismissed the voicemail and tried to rest. At 11:47 PM, three slow knocks sounded "
            "— the distinctive 'Shave and a Haircut' pattern used by a close friend who moved away. "
            "The silence after is thick."
        ),
        "tone": "dread",
        "choices": {
            "look through the peephole": "vm_check_door",
            "pull the covers over your head": "vm_clock",
        },
        "arc": "confrontation",
    },

    "vm_check_door": {
        "text": (
            "You move toward the door without breathing. The floorboards are silent beneath you. "
            "They are never silent.\n\n"
            "You press your eye to the peephole.\n\n"
            "The hallway light is stuttering badly. In the gaps between flickers — the hallway is empty.\n\n"
            "Then you look down.\n\n"
            "Your welcome mat has been flipped over. On the underside, in something dark and smeared:\n\n"
            "SOON.\n\n"
            "The deadbolt is still locked. But the security chain sways gently, as if someone just "
            "let it go from the inside."
        ),
        "scene_prompt": (
            "The player moved to the door. The floorboards made no sound — they always creak. "
            "Through the peephole, the hallway light was stuttering, revealing an empty hall. "
            "But the welcome mat was flipped over, with something dark smeared on the underside: SOON. "
            "The deadbolt is locked, but the security chain is swaying gently as if just released."
        ),
        "tone": "threshold",
        "choices": {
            "open the door": "end_loop",
            "back away and barricade the bedroom": "end_safe",
        },
        "arc": "resolution",
    },

    "vm_clock": {
        "text": (
            "You sit in the dark and watch the clock.\n\n"
            "11:51. 11:56. 11:59.\n\n"
            "At midnight, the voicemail deletes itself. No prompt. No confirmation. Just gone, "
            "like it was never there.\n\n"
            "You sit very still for a long time after that.\n\n"
            "In the morning you won't be sure it ever existed — except for the way your hands "
            "won't stop shaking."
        ),
        "scene_prompt": (
            "The player sat in the dark and watched the clock from 11:51 to midnight. Nothing came. "
            "At midnight the voicemail deleted itself. By morning they are unsure it was real — "
            "except for shaking hands."
        ),
        "tone": "loss",
        "choices": {
            "check the door in daylight": "end_safe",
            "never check. never think about it again": "end_static",
        },
        "arc": "resolution",
    },

    "end_safe": {
        "text": (
            "You drag the dresser in front of the bedroom door and sit with your back against the bed "
            "until the light changes.\n\n"
            "Morning comes. Thin and grey and real.\n\n"
            "You check every room. Nothing. The kitchen is spotless. The welcome mat is right-side up. "
            "No marks. No swaying chain. The apartment is just an apartment.\n\n"
            "The voicemail is gone. The call log is clean.\n\n"
            "You almost believe it.\n\n"
            "Then you step into the bathroom. The mirror is fogged — more than the cold air explains "
            "— and traced in it, one careful finger:\n\n"
            "3:12 AM\n\n"
            "You open your outgoing calls with shaking hands.\n\n"
            "One call. 3:12 AM. Unknown number. Four seconds.\n\n"
            "You have no memory of waking up.\n\n"
            "You open the voicemail app.\n\n"
            "There is one new recording. Received 3:12 AM. Your voice. Barely holding together.\n\n"
            "\"Don't answer the door tonight. Please… it's already here.\"\n\n"
            "And in the background, behind your own terrified voice —\n\n"
            "Your toaster dings.\n\n"
            "From the kitchen, right now, through the wall —\n\n"
            "Your toaster dings."
        ),
        "scene_prompt": (
            "The player survived the night barricaded in the bedroom. Morning came clean and ordinary. "
            "But the bathroom mirror holds a message traced in steam — 3:12 AM — and the outgoing call "
            "log confirms a 4-second call to an eleven-digit number at that time. A new voicemail has "
            "arrived, in their own voice, with the toaster dinging in the background."
        ),
        "tone": "threshold",
        "choices": {
            "you made the call. you were always going to make the call.": "intro",
        },
        "arc": "end",
    },

    "end_loop": {
        "text": (
            "You open the door.\n\n"
            "The hallway is gone. Just darkness — not an absence of light but a presence of something else, "
            "depth without end, cold that feels intentional.\n\n"
            "Your phone is already in your hand. You don't remember picking it up.\n\n"
            "The number is already dialing. You don't remember typing it.\n\n"
            "It rings once. You hear yourself answer — confused, not yet afraid.\n\n"
            "And you understand what you have to do. What you already did. What you are doing right now "
            "for the first time and the last time simultaneously.\n\n"
            "You open your mouth.\n\n"
            "\"Don't answer the door tonight.\" Your voice comes out ragged. Running. Hiding. "
            "\"Please… it's already here.\"\n\n"
            "Behind you, from your dark and empty kitchen —\n\n"
            "The toaster dings.\n\n"
            "You haven't used it in two days.\n\n"
            "The door swings shut."
        ),
        "scene_prompt": (
            "The player opened the door and stepped into absolute darkness — not absence of light but "
            "presence of void. The phone was already dialing an unknown number. They heard themselves "
            "answer. They understood what had to be said, and said it: the warning, in their own terrified "
            "voice. The toaster dinged from the empty kitchen behind them."
        ),
        "tone": "loss",
        "choices": {
            "you were the warning. you were always the warning.": "intro",
        },
        "arc": "end",
    },

    "end_static": {
        "text": (
            "You delete the voicemail. You factory reset the phone. You change your number, move apartments, "
            "and tell yourself it was a bad night, nothing more.\n\n"
            "For a while, that works.\n\n"
            "Then the small things start.\n\n"
            "Your reflection in dark windows lags. Half a second behind. Maybe less.\n\n"
            "People mid-conversation lose their train of thought and glance around the room, faintly puzzled, "
            "before carrying on.\n\n"
            "Your voice on recordings sounds like it's coming from a different room than the one "
            "you were standing in.\n\n"
            "You buy a new toaster. First morning in the new apartment, you haven't touched it yet, "
            "still unpacking —\n\n"
            "It dings.\n\n"
            "You understand then. You didn't escape. You became the gap in the recording — present enough "
            "to hear, not solid enough to hold.\n\n"
            "Somewhere, in an apartment that used to be yours, a phone is vibrating against a nightstand.\n\n"
            "The voicemail is about to play.\n\n"
            "You are about to play."
        ),
        "scene_prompt": (
            "The player tried to erase the night — reset, moved, changed their number. But they are "
            "becoming the gap in the recording. Their reflection lags. Their voice sounds distant. "
            "A new toaster in a new apartment dings before they've used it. "
            "The loop has found a new home inside them."
        ),
        "tone": "loss",
        "choices": {
            "you are the voice now.": "intro",
        },
        "arc": "end",
    },

}
